version: 2
updates:
  # Python dependencies
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "⬆️ deps"
      include: "scope"
    reviewers:
      - "reasoning-library/maintainers"
    assignees:
      - "reasoning-library/maintainers"
    open-pull-requests-limit: 5
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for stable dependencies
      - dependency-name: "numpy"
        update-types: ["version-update:semver-major"]

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "⬆️ actions"
      include: "scope"
    reviewers:
      - "reasoning-library/maintainers"
    assignees:
      - "reasoning-library/maintainers"
    open-pull-requests-limit: 3